### ISSUE TITLE
怎么使用MVC 开发   做成一个单例模式

### ISSUE THREAD

**Issue by alukaka** [DennisMao/eswiftBLE#1]
我想在多个界面进行蓝牙操作 把蓝牙manager做成一个model  比如一个界面是选择蓝牙   另一个界面是进行数据收发   第二个界面是经过第一个界面选择的蓝牙 总不能每个view都要重新扫描  重新连接吧    
谢谢

**Comment by DennisMao** [comment]
无需，第一个界面用CentralManager连接后 会返回 CBPeripheral，第二个页面传入这个CBPeripheral的数据结构进行操作即可。无需重新扫描。只要连接到CBPeripheral后面的事情跟Manager关系就不大了

**Comment by DennisMao** [comment]
再补充。1、多个页面都可以使用这个CBPeripheral，使用前建议先判断是否仍然在连接状态。如果中间连接断开的话，对设备进行操作是会报错的。2、建议当当前设备链接断开时候，自动跳转回去设备搜索页面或者弹出提示框

**Comment by alukaka** [comment]
恩   我今早也研究出来了   谢谢指教
